# Numpy - part 1.

In [2]:
import numpy as np

### 1. Numpy 배열(N-Dimensional array)

    모든 원소가 같은 자료형이어야 한다.

    원소의 갯수를 바꿀 수 없다.

In [3]:
a = np.array([1,3,4,7], float)
a

array([1., 3., 4., 7.])

In [5]:
a.dtype, a.shape, a.ndim, a.size

# dtype = data type(64비트 기본설정 = double presion , 32비트일 경우 sigle precision)
# shape = 모양
# size = element갯수
# ndim = 배열의 차수

(dtype('float64'), (4,), 1, 4)

In [8]:
# vector(1차원)
a = np.array([1,3,4,7], float)
a

array([1., 3., 4., 7.])

In [9]:
# Matrix(2차원)
b = np.array([[1,2,4],[4,3,9],[3,7,8]])
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [10]:
b.dtype, b.shape, b.ndim, b.size

(dtype('int32'), (3, 3), 2, 9)

In [11]:
# Tensor(3차원)
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [12]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3, 4), 3, 24)

In [13]:
# dtype
np.array([1,2,3,4], dtype=np.uint8)


array([1, 2, 3, 4], dtype=uint8)

In [14]:
#reshape
c.size

24

In [16]:
c.reshape(4,6)      # size가 같으면 reshape 가능(요소 개수 =)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [19]:
c.reshape(3,-1)     # -1은 한번만 사용 가능함

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
c.reshape(3,-1,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
a.reshape(4,-1)

array([[1.],
       [3.],
       [4.],
       [7.]])

In [23]:
# shape은 튜플
b.reshape(-1,)

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

In [25]:
b.flatten()

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

### 2. Indexing and slicing

In [27]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a[1][1], a[1,1], a[-1,-2]

(5, 5, 5)

In [31]:
a[1, :2]

array([4, 5])

In [32]:
a[:,1:]

array([[2, 3],
       [5, 6]])

In [34]:
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [36]:
b[:2, 1:]

array([[2, 4],
       [3, 9]])

In [38]:
b[1:, :2]

array([[4, 3],
       [3, 7]])

In [45]:
b[:2,::2]

## 슬라이싱 연습 필요!

array([[1, 4],
       [4, 9]])

### 3. Numpy 배열생성

In [46]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [48]:
np.arange(1,4.1,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [49]:
l = np.arange(1,4.1,0.5).tolist()
l

[1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]

In [54]:
np.arange(-2, 2.01, 0.02).size

201

In [52]:
# linear space
np.linspace(-2, 2, 201).size

201

    -ones, zeros, empty

In [55]:
np.ones(shape=(10, ), dtype=np.int16)             #데이터를 1로 채워라

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [56]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
np.zeros(4)

array([0., 0., 0., 0.])

In [59]:
np.empty(4)         #공간만 생성

array([0., 0., 0., 0.])

    - 대각선: identity, eye

In [63]:
# 정방형 (n x n)
np.identity(3, dtype=np.int16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [65]:
#직사각형 모양(N x M    )
np.eye(N=3, M=5, dtype=np.int16)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int16)

In [66]:
np.eye(3, 5, k=1, dtype=np.int8)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

    -데이터 분포에 따른 random sampling

In [67]:
np.random.seed(2021)

In [68]:
np.random.random(4)

array([0.60597828, 0.73336936, 0.13894716, 0.31267308])

In [70]:
np.random.normal(10, 4, 4)

array([12.22350333,  7.17798285, 14.52343305, 12.58000735])

In [73]:
# 표준 정규분포
np.random.rand(4)   # np.random.normal(0, 1, 4)

array([0.57430429, 0.37116085, 0.45214524, 0.20185025])

In [74]:
# 균등분포(uniform) 분포
np.random.uniform(3, 4, 4)

array([3.56930512, 3.19509597, 3.58370402, 3.47631347])

In [79]:
# 이항분포, t-분포   (확률과 통계 공부...)