# [Numpy 기초] 기본 연습문제
출처: https://deeptm.blogspot.com/2020/04/numpy-numpy.html

In [1]:
import numpy as np

### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [2]:
a = np.zeros(12).reshape(3,4)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

       array([[ 1.,  2.,  3.,  4.],
              [ 5.,  6.,  7.,  8.],
              [ 9., 10., 11., 12.]])

In [4]:
for i in range(3):
    for k in range(4):
        a[i,k] = 4*i + k+1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

    array([[5., 6., 7., 8.]])

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

    array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

array([1., 2., 3., 4., 5., 6.])

### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

### 8. a와 b의 요소곱을 하여 c에 저장하시오.

### 9. b의 전치행렬을 구하여 d에 저장하시오.

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

### 12. e에 대하여 각 열의 합을 계산하시오.