In [3]:
import numpy as np

# 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.

    10 20 30 40
    50 60 70 80

In [3]:
np.arange(10,90,10).reshape(2,4)


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [5]:
# ++ 강사님 방법

np.arange(1,9).reshape(2,4) *10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

# 2. 다음 행렬과 같은 행렬이 있다.

    m = np.array([[ 0, 1, 2, 3, 4],
    [ 5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14]])
    1) 이 행렬에서 값 7 을 인덱싱한다.
    2) 이 행렬에서 값 14 을 인덱싱한다.
    3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
    4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
    5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [7]:
m = np.array([[ 0, 1, 2, 3, 4],
[ 5, 6, 7, 8, 9],
[10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### slice 갯수에 따라 차원이 결정 됨

In [55]:
#1) 이 행렬에서 값 7 을 인덱싱한다.

m[1,2] 

7

In [54]:
#2) 이 행렬에서 값 14 을 인덱싱한다.

m[-1,-1]

14

In [53]:
#3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.

m[1,1:3]

array([6, 7])

In [52]:
#4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.

m[1:,2]

array([ 7, 12])

In [51]:
#5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

m[:2,3:]

array([[3, 4],
       [8, 9]])

# 3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
    1) 이 배열에서 3의 배수를 찾아라.
    2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
    3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [62]:
vector = m.reshape(-1)
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
# 다르게 변환하는 법
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
#1) 이 배열에서 3의 배수를 찾아라.

vector[vector % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [45]:
#2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.

vector[vector % 4 == 1]

array([ 1,  5,  9, 13])

In [69]:
vector2 = (vector % 3 == 0) & (vector % 4 == 1)
vector[vector2]

array([9])

In [10]:
# 다른 방법
f[np.logical_and(f%3==0, f%4==1)]

array([9])

# 4. 값을 직접 입력하지 말고 우측의 행렬을 만드시오.
    2, 1, 0, 0, 0
    3, 2, 1, 0, 0
    0, 3, 2, 1, 0
    0, 0, 3, 2, 1
    0, 0, 0, 3, 2

In [12]:
table1 = np.eye(M=5,N=5,k=1,dtype=int)
table2 = np.eye(M=5,N=5,dtype=int)
table3 = np.eye(M=5,N=5,k=-1,dtype=int)
table1 + table2 *2 + table3*3


array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

In [14]:
#줄이기
table = np.eye(5,5,1,dtype=int)+np.eye(5,5,dtype=int)*2+np.eye(5,5,-1,dtype=int)*3
table

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

# 5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오.
    1) 전체의 최댓값
    2) 각 행의 합
    3) 각 행의 최댓값
    4) 각 열의 평균
    5) 각 열의 최솟값

In [80]:
import random 

In [20]:
rand = np.random.uniform(0, 10, 30).reshape(5,6).round(4)
rand

array([[0.0996, 9.3057, 8.5205, 4.1368, 6.0194, 0.0245],
       [5.4414, 5.0613, 6.0212, 6.3542, 9.6447, 1.3911],
       [8.6577, 8.4331, 0.9128, 8.5836, 9.7078, 1.6843],
       [2.1767, 4.6439, 4.5497, 2.7729, 7.615 , 4.0662],
       [4.4894, 9.2326, 4.8784, 1.9468, 1.1924, 4.6346]])

In [21]:
#1) 전체의 최댓값
rand.max()

9.7078

In [26]:
#2) 각 행의 합
rand.sum(axis=1)

array([28.1065, 33.9139, 37.9793, 25.8244, 26.3742])

In [27]:
#3) 각 행의 최댓값
rand.max(axis=1)

array([9.3057, 9.6447, 9.7078, 7.615 , 9.2326])

In [28]:
#4) 각 열의 평균
rand.mean(axis=0)

array([4.17296, 7.33532, 4.97652, 4.75886, 6.83586, 2.36014])

In [29]:
#5) 각 열의 최솟값
rand.min(axis=0)

array([0.0996, 4.6439, 0.9128, 1.9468, 1.1924, 0.0245])

# 6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.
    학번:   array([[ 1, 2, 3, 4],
    영어성적: [ 46, 99, 100, 71],
    수학성적: [ 81, 59, 90, 100]])

In [31]:
test = np.array([[ 1, 2, 3, 4],
[ 46, 99, 100, 71],
[ 81, 59, 90, 100]])

In [55]:
test1 = test[:,test[1].argsort()[::-1]]
test1

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [56]:
# 강사님 방법
indices= np.argsort(test[1])
indices

array([0, 3, 1, 2], dtype=int64)

In [47]:
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [50]:
test[:,indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [54]:
# 한줄로 줄이기!
test[:,np.argsort(test[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

# 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오.

In [58]:
#[].()은 다름... []는 마지막 값 포함, ()은 마지막 값 비포함
dice100 = np.random.randint(1,7,100)
dice100.mean()

3.62

In [60]:
# dice100 array에서의 고유값
np.unique(dice100)

array([1, 2, 3, 4, 5, 6])

In [61]:
#dice100 array에서 고유값 및 그 갯수
np.unique(dice100, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([17, 15, 17, 13, 16, 22], dtype=int64))

In [62]:
unique, counts = np.unique(dice100, return_counts=True)
dict(zip(unique,counts))

{1: 17, 2: 15, 3: 17, 4: 13, 5: 16, 6: 22}

# 8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.

In [83]:
np.random.seed(2021)
price =10000
rate = np.random.normal(0, 0.01, 250)
price_list = []
for i in range(250):
    price = price + np.round(price*rate[i])
    price_list.append(price)

price_array = np.array(price_list, dtype=np.int32)
price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])

In [84]:
np.random.seed(2021)
price =10000
rate = np.random.normal(0, 0.01, 250)
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price*rate[i])
    price_array[i] = price

price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])