In [1]:
import numpy as np

# 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.

    10 20 30 40
    50 60 70 80

In [3]:
np.arange(10,90,10).reshape(2,4)


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

# 2. 다음 행렬과 같은 행렬이 있다.

    m = np.array([[ 0, 1, 2, 3, 4],
    [ 5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14]])
    1) 이 행렬에서 값 7 을 인덱싱한다.
    2) 이 행렬에서 값 14 을 인덱싱한다.
    3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
    4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
    5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [21]:
m = np.array([[ 0, 1, 2, 3, 4],
[ 5, 6, 7, 8, 9],
[10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
#1) 이 행렬에서 값 7 을 인덱싱한다.

m[1,2] 

7

In [54]:
#2) 이 행렬에서 값 14 을 인덱싱한다.

m[-1,-1]

14

In [53]:
#3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.

m[1,1:3]

array([6, 7])

In [52]:
#4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.

m[1:,2]

array([ 7, 12])

In [51]:
#5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

m[:2,3:]

array([[3, 4],
       [8, 9]])

# 3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
    1) 이 배열에서 3의 배수를 찾아라.
    2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
    3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [62]:
vector = m.reshape(-1)
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
#1) 이 배열에서 3의 배수를 찾아라.

vector[vector % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [45]:
#2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.

vector[vector % 4 == 1]

array([ 1,  5,  9, 13])

In [69]:
vector2 = (vector % 3 == 0) & (vector % 4 == 1)
vector[vector2]

array([9])

# 4. 값을 직접 입력하지 말고 우측의 행렬을 만드시오.
    2, 1, 0, 0, 0
    3, 2, 1, 0, 0
    0, 3, 2, 1, 0
    0, 0, 3, 2, 1
    0, 0, 0, 3, 2

In [174]:
table1 = np.eye(M=5,N=5,k=1)
table2 = np.eye(M=5,N=5)
table3 = np.eye(M=5,N=5,k=-1)
table1 + table2 *2 + table3*3


array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [176]:
#줄이기
table = np.eye(M=5,N=5,k=1)+np.eye(M=5,N=5)*2+np.eye(M=5,N=5,k=-1)*3
table

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

# 5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오.
    1) 전체의 최댓값
    2) 각 행의 합
    3) 각 행의 최댓값
    4) 각 열의 평균
    5) 각 열의 최솟값

In [80]:
import random 

In [93]:
rand = np.random.uniform(1, 10, 30).reshape(5,6)
rand

array([[7.89465427, 6.00761577, 5.51793246, 5.18158595, 3.15020849,
        4.08105978],
       [8.51980053, 8.82422805, 9.27388834, 3.39622523, 5.7073644 ,
        4.6997667 ],
       [1.85215402, 8.20001791, 6.25267101, 9.79244374, 4.21648593,
        1.3791701 ],
       [2.95135453, 2.67879513, 7.28140621, 8.54718583, 8.84937093,
        3.04592514],
       [9.28511043, 3.05271857, 9.21421152, 2.19944974, 8.47074318,
        3.74581016]])

In [94]:
#1) 전체의 최댓값
rand.max()

9.792443743176667

In [95]:
#2) 각 행의 합
rand.sum(axis=0)

array([30.50307378, 28.76337544, 37.54010955, 29.11689049, 30.39417293,
       16.95173188])

In [96]:
#3) 각 행의 최댓값
rand.max(axis=0)

array([9.28511043, 8.82422805, 9.27388834, 9.79244374, 8.84937093,
       4.6997667 ])

In [99]:
#4) 각 열의 평균
rand.mean(axis=1)

array([5.30550945, 6.73687887, 5.28215712, 5.5590063 , 5.99467393])

In [98]:
#5) 각 열의 최솟값
rand.min(axis=1)

array([3.15020849, 3.39622523, 1.3791701 , 2.67879513, 2.19944974])

# 6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.
    학번:   array([[ 1, 2, 3, 4],
    영어성적: [ 46, 99, 100, 71],
    수학성적: [ 81, 59, 90, 100]])

In [111]:
test = np.array([[ 1, 2, 3, 4],
[ 46, 99, 100, 71],
[ 81, 59, 90, 100]])

In [126]:
test1 = test[:,test[1].argsort()]
test1

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

# 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오.

In [134]:
dice100 = np.random.randint(1,6,100)
dice100.mean()

3.0

# 8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.

In [180]:
price = 10000
stock = price + np.random.normal(0,1,250)
stock

array([10001.84718321, 10000.71086524,  9998.98762391, 10000.12072824,
        9999.00817893,  9999.89701517, 10001.18712681, 10001.07426682,
       10001.52261217,  9999.34247532,  9999.47543152,  9999.04663967,
       10000.27306115, 10001.37487373,  9999.82483793, 10001.13986062,
       10000.27774761, 10001.38113246, 10000.88902959, 10000.48259827,
       10000.93024374,  9999.84398899, 10002.07719017,  9999.47094691,
       10000.96907006, 10000.11587058, 10000.56222628, 10000.61481484,
        9998.37294907, 10000.36907706, 10000.43843942, 10000.00304311,
        9999.01673679,  9999.01238107,  9998.83417822,  9999.40081171,
        9999.63175964,  9998.84130405,  9999.11592312,  9999.87578404,
       10000.52058035,  9999.34086505, 10000.01333008,  9999.71393967,
        9999.79827432,  9997.99072801,  9999.0679133 , 10000.07132394,
       10000.56586421, 10000.79167937,  9999.44642719,  9999.94710348,
        9999.29150654,  9999.70599209,  9999.74268099, 10000.40188502,
      